version: "2"

run:
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/mattermost/mattermost-plugin-msteams-meetings

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace

  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US

  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - unused
        path: server/configuration.go
      - linters:
          - bodyclose
          - scopelint
        path: _test\.go


