// Copyright (c) 2020-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// This file is automatically generated. Do not modify it manually.

package main

import "github.com/mattermost/mattermost/server/public/model"

var manifest = model.Manifest{
	Id:      "com.mattermost.msteamsmeetings",
	Version: "2.2.0",
}
